export const API_ENDPOINTS = {
  USERS: "/users",
  LOGIN: "/admin-panel-login",
  CARS: "/cars",
  ADS: "/ads",
  CARS_SOLD_STATS: "/sold-cars-stats",
  CARS_SOLD_ON_PLATFORM_STATS: "/sold-cars-by-platform-stats",
  MOST_VIEWED: "/top-viewed",
  CARS_STATS: "/cars-stats",
  OWNERS_STATS: "/car-owners-stats",
  USER_INACTIVE: "/inactive-user",
  USER_BAN: "/ban-user",
  USER_UNBAN: "/unban-user",
  USER_ACTIVE: "/active-user",
  MARK_INACTIVE: "/mark-inactive",
  MARK_ACTIVE: "/mark-active",
  MARK_SOLD: "/mark-sold",
  MARK_UNSOLD: "/mark-unsold",
  MARK_BAN: "/ban",
  MARK_UNBAN: "/unban",
  CAR_MAKES: "/makes",
  MAKE_MODELS: "/models/?make_id=",
  MODEL_VERSIONS: "/versions?model_id=",
  UPDATE_PASSWORD: "/updateUserPassword",
};
