name: s3-depl

on:
  push:
    branches:
      - develop
      - r/2143.1-0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build React App - Dev
        if: github.ref == 'refs/heads/develop'
        run: npm install --legacy-peer-deps && npm run build-dev
        env:
         CI: false
      - name: Build React App - Prod
        if: github.ref == 'refs/heads/r/2143.1-0'
        run: npm install && npm run build-prod
        env:
         CI: false
      - name: Deploy app build to Development S3 bucket
        if: github.ref == 'refs/heads/develop'
        run: aws s3 sync ./build/ s3://admin.carokta.com --delete
      - name: Deploy app build to Production S3 bucket
        if: github.ref == 'refs/heads/r/2143.1-0'
        run: aws s3 sync ./build/ s3://prod-admin.carokta.com --delete
      - name: Development CDN Cache invalidation
        if: github.ref == 'refs/heads/develop'
        run:  aws cloudfront create-invalidation --distribution-id "E1W481MNO4O4HD" --paths "/*"
      - name: Production CDN Cache invalidation
        if: github.ref == 'refs/heads/r/2143.1-0'
        run:  aws cloudfront create-invalidation --distribution-id "E153Q852I8DRCX" --paths "/*"
